// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2IBfupQCVAsrkcsNS9mCV4QUuZBK6FeY',
    appId: '1:1005419115490:web:ebf79bc20e0a3ecabb3fbb',
    messagingSenderId: '1005419115490',
    projectId: 'senior-project-regdog',
    authDomain: 'senior-project-regdog.firebaseapp.com',
    storageBucket: 'senior-project-regdog.firebasestorage.app',
    measurementId: 'G-PSFNRNECXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHy1WsEKWSEh8jW4NSoSuht7Ytfc9JQU',
    appId: '1:1005419115490:android:274872b2a6bcdc55bb3fbb',
    messagingSenderId: '1005419115490',
    projectId: 'senior-project-regdog',
    storageBucket: 'senior-project-regdog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi_ZYVzCpPN8IEIZSLOF_kSvCUCBe9OU8',
    appId: '1:1005419115490:ios:13a7f53de10cf743bb3fbb',
    messagingSenderId: '1005419115490',
    projectId: 'senior-project-regdog',
    storageBucket: 'senior-project-regdog.firebasestorage.app',
    androidClientId: '1005419115490-6go39g3ecjo7b1biviljmu5c8gvc7om5.apps.googleusercontent.com',
    iosClientId: '1005419115490-dgqlalqid6bct5e0mip0q18ga6a6libr.apps.googleusercontent.com',
    iosBundleId: 'com.example.regdogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi_ZYVzCpPN8IEIZSLOF_kSvCUCBe9OU8',
    appId: '1:1005419115490:ios:13a7f53de10cf743bb3fbb',
    messagingSenderId: '1005419115490',
    projectId: 'senior-project-regdog',
    storageBucket: 'senior-project-regdog.firebasestorage.app',
    androidClientId: '1005419115490-6go39g3ecjo7b1biviljmu5c8gvc7om5.apps.googleusercontent.com',
    iosClientId: '1005419115490-dgqlalqid6bct5e0mip0q18ga6a6libr.apps.googleusercontent.com',
    iosBundleId: 'com.example.regdogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2IBfupQCVAsrkcsNS9mCV4QUuZBK6FeY',
    appId: '1:1005419115490:web:c790f5289eb2f226bb3fbb',
    messagingSenderId: '1005419115490',
    projectId: 'senior-project-regdog',
    authDomain: 'senior-project-regdog.firebaseapp.com',
    storageBucket: 'senior-project-regdog.firebasestorage.app',
    measurementId: 'G-DY6FCS6BKJ',
  );

}